package TryCatch;

public class TryCatch {

	
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub

		int a=7;
		int b=0;	
		
		try {
			
		int	c= a/b;
		
		}
		
		catch(ArithmeticException et) {
			
			System.out.println("I was catched by arithematic catch block");
		}
		
		catch(Exception e) {
			
			System.out.println("I got an error and hence printing this");
		}
	
		
	
	
	}
	
	

}
